export const AVAILABLE_COLUMNS = {
  students: [
    'school_student_id',
    'first_name',
    'last_name',
    'email',
    'dob',
    'enrollment_date',
    'graduation_year',
    'current_gpa',
    'academic_status',
    'grade_level',
    'gender',
    'ethnicity',
    'state_id',
    'street_address',
    'city',
    'state',
    'zip',
    'guardian1_name',
    'guardian1_email',
    'guardian1_relationship',
    'guardian2_name',
    'guardian2_email',
    'guardian2_relationship'
  ],
  teachers: [
    'school_teacher_id',
    'first_name',
    'last_name',
    'email',
    'dob',
    'qualification1',
    'qualification2',
    'qualification3',
    'certification1',
    'certification2',
    'certification3'
  ],
  admins: [
    'first_name',
    'last_name',
    'email',
    'phone',
    'admin_user_type'
  ],
  classrooms: [
    'classroom_name',
    'classroom_teacher_id',
    'school_year',
    'grade',
    'school_id'
  ],
  attendance: [
    // Basic student info
    'school_student_id', 'Student', 'ID', 'State ID', 'Current School', 'Grade', 'Race',
    'Gender', 'Age (Yrs)', 'Age (Yrs, Mos)', 'ZIP Code', 'Home Language',
    'Time in District (Yrs)', 'Time in District (Yrs, Mos)', 'Time in District (Level)',
    'Time in School (Yrs)', 'Time in School (Yrs, Mos)', 'Ethnicity', 'Native Country',

    // Attendance data
    '2023-24 Gr 3 Attendance', 'Result Date', 'Level', 'Daily Attendance Rate',
    'Total Days Present', 'Total Days Possible', 'FY Absences (Total Days)',
    'FY Absences (Excused Days)', 'FY Absences (Unexcused Days)', 'FY Tardies (Total Days)',
    'FY Tardies (Excused Days)', 'FY Tardies (Unexcused Days)', 'FY Virtual (Days)',

    // Marking Period 1
    'MP1 (Level - ScoreCustomN_1)', 'MP1 (Daily Attendance Rate)', 'MP1 (Total Days Present)',
    'MP1 (Total Days Possible)', 'MP1 Absences (Total Days)', 'MP1 Absences (Excused Days)',
    'MP1 Absences (Unexcused Days)', 'MP1 Tardies (Total Days)', 'MP1 Tardies (Excused Days)',
    'MP1 Tardies (Unexcused Days)', 'MP1 Virtual (Days)',

    // Marking Period 2
    'MP2 (Level - ScoreCustomN_1)', 'MP2 (Daily Attendance Rate)', 'MP2 (Total Days Present)',
    'MP2 (Total Days Possible)', 'MP2 Absences (Total Days)', 'MP2 Absences (Excused Days)',
    'MP2 Absences (Unexcused Days)', 'MP2 Tardies (Total Days)', 'MP2 Tardies (Excused Days)',
    'MP2 Tardies (Unexcused Days)', 'MP2 Virtual (Days)',

    // Marking Period 3
    'MP3 (Level - ScoreCustomN_1)', 'MP3 (Daily Attendance Rate)', 'MP3 (Total Days Present)',
    'MP3 (Total Days Possible)', 'MP3 Absences (Total Days)', 'MP3 Absences (Excused Days)',
    'MP3 Absences (Unexcused Days)', 'MP3 Tardies (Total Days)', 'MP3 Tardies (Excused Days)',
    'MP3 Tardies (Unexcused Days)', 'MP3 Virtual (Days)',

    // Marking Period 4
    'MP4 (Level - ScoreCustomN_1)', 'MP4 (Daily Attendance Rate)', 'MP4 (Total Days Present)',
    'MP4 (Total Days Possible)', 'MP4 Absences (Total Days)', 'MP4 Absences (Excused Days)',
    'MP4 Absences (Unexcused Days)', 'MP4 Tardies (Total Days)', 'MP4 Tardies (Excused Days)',
    'MP4 Tardies (Unexcused Days)', 'MP4 Virtual (Days)',

    // Semester and Term data
    'S1 (Level - ScoreCustomN_1)', 'S1 (Daily Attendance Rate)', 'S1 (Total Days Present)',
    'S1 (Total Days Possible)', 'S1 Absences (Total Days)', 'S1 Absences (Excused Days)',
    'S1 Absences (Unexcused Days)', 'S1 Tardies (Total Days)', 'S1 Tardies (Excused Days)',
    'S1 Tardies (Unexcused Days)', 'S1 Virtual (Days)',
    'S2 (Level - ScoreCustomN_1)', 'S2 (Daily Attendance Rate)', 'S2 (Total Days Present)',
    'S2 (Total Days Possible)', 'S2 Absences (Total Days)', 'S2 Absences (Excused Days)',
    'S2 Absences (Unexcused Days)', 'S2 Tardies (Total Days)', 'S2 Tardies (Excused Days)',
    'S2 Tardies (Unexcused Days)', 'S2 Virtual (Days)',
    'T1 (Daily Attendance Rate)', 'T1 (Total Days Present)', 'T1 (Total Days Possible)',
    'T1 Absences (Total Days)', 'T1 Absences (Excused Days)', 'T1 Absences (Unexcused Days)',
    'T1 Tardies (Total Days)', 'T1 Tardies (Excused Days)', 'T1 Tardies (Unexcused Days)',
    'T1 Virtual (Days)',
    'T2 (Daily Attendance Rate)', 'T2 (Total Days Present)', 'T2 (Total Days Possible)',
    'T2 Absences (Total Days)', 'T2 Absences (Excused Days)', 'T2 Absences (Unexcused Days)',
    'T2 Tardies (Total Days)', 'T2 Tardies (Excused Days)', 'T2 Tardies (Unexcused Days)',
    'T2 Virtual (Days)',
    'T3 (Daily Attendance Rate)', 'T3 (Total Days Present)', 'T3 (Total Days Possible)',
    'T3 Absences (Total Days)', 'T3 Absences (Excused Days)', 'T3 Absences (Unexcused Days)',
    'T3 Tardies (Total Days)', 'T3 Tardies (Excused Days)', 'T3 Tardies (Unexcused Days)',
    'T3 Virtual (Days)',

    // Other fields
    'attendance_year', 'school_id', 'School ID', 'schoolid', 'SchoolID',
    
    // Additional common variations
    'Date', 'Export Date', 'Days Present', 'Present Days', 'Days Possible', 
    'Possible Days', 'Total Absences', 'Absences Total', 'Excused Absences', 
    'Excused', 'Unexcused Absences', 'Unexcused', 'Tardies', 'Total Tardies',
    'Daily Rate', 'MP1 Rate', 'MP2 Rate', 'MP3 Rate', 'MP4 Rate'
  ],
  individualized_needs: [
    'school_student_id',
    'student_id',
    'ID',
    'StudentID',
    'Student ID',
    'type',
    'need_type',
    'Need Type',
    'status',
    'Status',
    'spec_ed_status',
    'Spec Ed Status',
    'Special Education Status',
    'spec_ed',
    'Spec Ed',
    'Special Education',
    'home_language',
    'Home Language',
    'Primary Language',
    'has_active_iep',
    'Has Active IEP Or Related Services',
    'Active IEP',
    'IEP Status',
    'ell_active',
    'Ell Active',
    'ELL Active',
    'English Language Learner',
    'additional_notes',
    'notes',
    'Notes',
    'Additional Notes',
    'Comments'
  ]
};

// Column descriptions for tooltips and help text
export const COLUMN_DESCRIPTIONS = {
  // Student columns
  'school_student_id': 'Unique identifier for the student within the school system',
  'first_name': 'Student\'s first name',
  'last_name': 'Student\'s last name',
  'email': 'Student\'s email address',
  'dob': 'Date of birth (YYYY-MM-DD)',
  'enrollment_date': 'Date when student enrolled (YYYY-MM-DD)',
  'graduation_year': 'Expected graduation year',
  'current_gpa': 'Current grade point average',
  'academic_status': 'Current academic status (active, inactive, etc.)',
  'grade_level': 'Current grade level',
  'gender': 'Student\'s gender',
  'ethnicity': 'Student\'s ethnicity',
  'state_id': 'State-issued student identifier',
  'street_address': 'Student\'s street address',
  'city': 'Student\'s city',
  'state': 'Student\'s state',
  'zip': 'Student\'s ZIP code',
  'guardian1_name': 'Name of primary guardian',
  'guardian1_email': 'Email of primary guardian',
  'guardian1_relationship': 'Relationship of primary guardian to student',
  'guardian2_name': 'Name of secondary guardian',
  'guardian2_email': 'Email of secondary guardian',
  'guardian2_relationship': 'Relationship of secondary guardian to student',

  // Teacher columns
  'school_teacher_id': 'Unique identifier for the teacher within the school system',
  'qualification1': 'Primary qualification or degree',
  'qualification2': 'Secondary qualification or degree',
  'qualification3': 'Tertiary qualification or degree',
  'certification1': 'Primary teaching certification',
  'certification2': 'Secondary teaching certification',
  'certification3': 'Tertiary teaching certification',

  // Admin columns
  'phone': 'Contact phone number',
  'admin_user_type': 'Type of administrator (school_admin, district_admin, etc.)',

  // Classroom columns
  'classroom_name': 'Name of the classroom',
  'classroom_teacher_id': 'UUID of the teacher assigned to the classroom (must match teacher_id from Teachers step)',
  'school_year': 'Academic year (e.g., 2024-2025)',
  'grade': 'Grade level for the classroom',
  'school_id': 'UUID of the school this classroom belongs to (automatically set from School step)',

  // Attendance columns
  'id': 'School-specific student identifier (must match existing student)',
  'record_date': 'Date of the attendance record (YYYY-MM-DD)',
  'total_days_present': 'Total number of days the student was present',
  'total_days_possible': 'Total number of possible attendance days',
  'fy_absences_total': 'Total absences for the full year',
  'fy_absences_excused': 'Number of excused absences for the full year',
  'fy_absences_unexcused': 'Number of unexcused absences for the full year',
  'fy_tardies_total': 'Total number of tardies for the full year',
  'attendance_year': 'Academic year for the attendance record (e.g., 2024-2025)',
  'daily_attendance_rate': 'Daily attendance rate as a percentage (0-100)',
  'mp1_attendance_rate': 'Marking period 1 attendance rate as a percentage (0-100)',
  'mp2_attendance_rate': 'Marking period 2 attendance rate as a percentage (0-100)',
  'mp3_attendance_rate': 'Marking period 3 attendance rate as a percentage (0-100)',
  'mp4_attendance_rate': 'Marking period 4 attendance rate as a percentage (0-100)',

  // Additional column variations
  'Student ID': 'Student identifier that matches school_student_id from Students step',
  'ID': 'Student identifier that matches school_student_id from Students step',
  'StudentID': 'Student identifier that matches school_student_id from Students step',
  'Result Date': 'Date of the attendance record (YYYY-MM-DD)',
  'Record Date': 'Date of the attendance record (YYYY-MM-DD)',
  'Date': 'Date of the attendance record (YYYY-MM-DD)',
  'Export Date': 'Date of the attendance record (YYYY-MM-DD)',
  'Days Present': 'Total number of days the student was present',
  'Present Days': 'Total number of days the student was present',
  'Total Days Present': 'Total number of days the student was present',
  'Days Possible': 'Total number of possible attendance days',
  'Possible Days': 'Total number of possible attendance days',
  'Total Days Possible': 'Total number of possible attendance days',
  'Total Absences': 'Total absences for the full year',
  'Absences Total': 'Total absences for the full year',
  'FY Absences (Total Days)': 'Total absences for the full year',
  'Excused Absences': 'Number of excused absences for the full year',
  'Excused': 'Number of excused absences for the full year',
  'FY Absences (Excused Days)': 'Number of excused absences for the full year',
  'Unexcused Absences': 'Number of unexcused absences for the full year',
  'Unexcused': 'Number of unexcused absences for the full year',
  'FY Absences (Unexcused Days)': 'Number of unexcused absences for the full year',
  'Tardies': 'Total number of tardies for the full year',
  'Total Tardies': 'Total number of tardies for the full year',
  'FY Tardies (Total Days)': 'Total number of tardies for the full year',
  'Daily Attendance Rate': 'Daily attendance rate as a percentage (0-100)',
  'Daily Rate': 'Daily attendance rate as a percentage (0-100)',
  'MP1 Attendance Rate': 'Marking period 1 attendance rate as a percentage (0-100)',
  'MP1 Rate': 'Marking period 1 attendance rate as a percentage (0-100)',
  'MP2 Attendance Rate': 'Marking period 2 attendance rate as a percentage (0-100)',
  'MP2 Rate': 'Marking period 2 attendance rate as a percentage (0-100)',
  'MP3 Attendance Rate': 'Marking period 3 attendance rate as a percentage (0-100)',
  'MP3 Rate': 'Marking period 3 attendance rate as a percentage (0-100)',
  'MP4 Attendance Rate': 'Marking period 4 attendance rate as a percentage (0-100)',
  'MP4 Rate': 'Marking period 4 attendance rate as a percentage (0-100)',
  'School ID': 'UUID of the school this attendance record belongs to',
  'schoolid': 'UUID of the school this attendance record belongs to',
  'SchoolID': 'UUID of the school this attendance record belongs to',
  'Level': 'Grade level of the student',
  'FY Virtual (Days)': 'Total number of virtual school days for the full year',
  'MP1 (Level - ScoreCustomN_1)': 'A custom score for the student in marking period 1',
  'MP1 (Total Days Present)': 'Total days present for marking period 1',
  'MP1 (Total Days Possible)': 'Total possible days for marking period 1',
  'MP1 Absences (Total Days)': 'Total absences for marking period 1',
  'MP1 Absences (Excused Days)': 'Excused absences for marking period 1',
  'MP1 Absences (Unexcused Days)': 'Unexcused absences for marking period 1',
  'MP1 Tardies (Total Days)': 'Total tardies for marking period 1',
  'MP1 Tardies (Excused Days)': 'Excused tardies for marking period 1',
  'MP1 Tardies (Unexcused Days)': 'Unexcused tardies for marking period 1',
  'MP1 Virtual (Days)': 'Virtual school days for marking period 1',

  // Individualized needs columns
  'student_id': 'Student identifier that matches school_student_id from Students step',
  'type': 'Type of individualized need (Special Education, English Language Learning, etc.)',
  'need_type': 'Type of individualized need (Special Education, English Language Learning, etc.)',
  'Need Type': 'Type of individualized need (Special Education, English Language Learning, etc.)',
  'status': 'Current status of the need (Active, Inactive, Pending, Completed)',
  'Status': 'Current status of the need (Active, Inactive, Pending, Completed)',
  'spec_ed_status': 'Special education program status',
  'Spec Ed Status': 'Special education program status',
  'Special Education Status': 'Special education program status',
  'spec_ed': 'Specific special education classification or disability',
  'Spec Ed': 'Specific special education classification or disability',
  'Special Education': 'Specific special education classification or disability',
  'home_language': 'Primary language spoken at home',
  'Home Language': 'Primary language spoken at home',
  'Primary Language': 'Primary language spoken at home',
  'has_active_iep': 'Whether student has an active IEP or related services (true/false)',
  'Has Active IEP Or Related Services': 'Whether student has an active IEP or related services (true/false)',
  'Active IEP': 'Whether student has an active IEP or related services (true/false)',
  'IEP Status': 'Whether student has an active IEP or related services (true/false)',
  'ell_active': 'Whether student is actively receiving English Language Learning services (true/false)',
  'Ell Active': 'Whether student is actively receiving English Language Learning services (true/false)',
  'ELL Active': 'Whether student is actively receiving English Language Learning services (true/false)',
  'English Language Learner': 'Whether student is actively receiving English Language Learning services (true/false)',
  'additional_notes': 'Additional notes about the student\'s individualized needs',
  'notes': 'Additional notes about the student\'s individualized needs',
  'Notes': 'Additional notes about the student\'s individualized needs',
  'Additional Notes': 'Additional notes about the student\'s individualized needs',
  'Comments': 'Additional notes about the student\'s individualized needs'
};

// Database schema column types for validation
export const COLUMN_TYPES = {
  'school_student_id': 'text',
  'first_name': 'text',
  'last_name': 'text',
  'email': 'text',
  'dob': 'date',
  'enrollment_date': 'date',
  'graduation_year': 'integer',
  'current_gpa': 'numeric',
  'academic_status': 'text',
  'grade_level': 'text',
  'gender': 'text',
  'ethnicity': 'text',
  'state_id': 'text',
  'street_address': 'text',
  'city': 'text',
  'state': 'text',
  'zip': 'text',
  'guardian1_name': 'text',
  'guardian1_email': 'text',
  'guardian1_relationship': 'text',
  'guardian2_name': 'text',
  'guardian2_email': 'text',
  'guardian2_relationship': 'text',
  'school_teacher_id': 'text',
  'qualification1': 'text',
  'qualification2': 'text',
  'qualification3': 'text',
  'certification1': 'text',
  'certification2': 'text',
  'certification3': 'text',
  'phone': 'text',
  'admin_user_type': 'text',
  'classroom_name': 'text',
  'classroom_teacher_id': 'uuid',
  'school_year': 'text',
  'grade': 'text',
  'school_id': 'uuid',
  'record_date': 'date',
  'total_days_present': 'integer',
  'total_days_possible': 'integer',
  'fy_absences_total': 'integer',
  'fy_absences_excused': 'integer',
  'fy_absences_unexcused': 'integer',
  'fy_tardies_total': 'integer',
  'attendance_year': 'text',
  'daily_attendance_rate': 'numeric',
  'mp1_attendance_rate': 'numeric',
  'mp2_attendance_rate': 'numeric',
  'mp3_attendance_rate': 'numeric',
  'mp4_attendance_rate': 'numeric',
  'type': 'text',
  'need_type': 'text',
  'status': 'text',
  'spec_ed_status': 'text',
  'spec_ed': 'text',
  'home_language': 'text',
  'has_active_iep': 'boolean',
  'ell_active': 'boolean',
  'additional_notes': 'text',
  'notes': 'text'
};